# Generated by Django 3.0.6 on 2020-06-16 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotifyassist', '0002_auto_20200615_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='account',
        ),
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artistlist',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='artists', to='spotifyassist.Artist'),
        ),
    ]
