# Generated by Django 3.0.6 on 2020-06-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyassist', '0003_auto_20200616_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.CharField(default=0, max_length=268),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
